# Generated by Django 3.2.13 on 2022-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gs1', models.IntegerField(default=0)),
                ('gs2', models.IntegerField(default=0)),
                ('gs3', models.IntegerField(default=0)),
                ('gs4', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=10)),
                ('types', models.CharField(max_length=20)),
            ],
        ),
    ]
