# Generated by Django 3.2.13 on 2022-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attack',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='defense',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gs1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gs2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gs3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gs4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='types',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
